[project]
name = "grove-base"
version = "0.1.0"
description = "GrovePI base code for designing sensor systems"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools]
packages = ["imu", "nfc", "smbus2"]
